fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 0.4.2
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile
      ref: 1.0.0
    sudo:
      repo: git://github.com/saz/puppet-sudo.git
      ref: v3.0.0
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 0.0.6
  symlinks:
    ovirt: "#{source_dir}"
