fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.2.2
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 1.1.2
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile
      ref: 1.1.2
    postgresql:
      repo: git://github.com/puppetlabs/puppetlabs-postgresql
      ref: 3.3.3
    sudo:
      repo: git://github.com/saz/puppet-sudo.git
      ref: v3.0.6
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 0.1.0
    concat: git://github.com/puppetlabs/puppetlabs-concat.git
    gpg_key: git://github.com/treydock/puppet-gpg_key.git
  symlinks:
    ovirt: "#{source_dir}"
